[project]
name = "myagent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "aiohappyeyeballs>=2.6.2",
    "aiohttp>=3.13.5",
    "annotated-types>=0.7.0",
    "anyio>=4.13.0",
    "autogen-agentchat>=0.7.5",
    "autogen-core>=0.7.5",
    "autogen-ext>=0.7.5",
    "certifi>=2026.5.20",
    "cffi>=2.0.0",
    "cryptography>=48.0.0",
    "dotenv>=0.9.9",
    "h11>=0.16.0",
    "httpcore>=1.0.9",
    "httpx>=0.28.1",
    "idna>=3.16",
    "jiter>=0.15.0",
    "langchain-core>=1.4.0",
    "langchain-openai>=1.2.2",
    "langgraph>=1.2.1",
    "langgraph-checkpoint>=4.1.1",
    "multidict>=6.7.1",
    "numpy>=2.4.6",
    "openai>=2.38.0",
    "orjson>=3.11.9",
    "pandas>=3.0.3",
    "plotly>=6.7.0",
    "pycparser>=3.0",
    "pydantic>=2.13.4",
    "pydantic-core>=2.46.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "serpapi>=1.0.2",
    "streamlit>=1.57.0",
    "tavily>=1.1.0",
    "torch>=2.12.0",
    "tqdm>=4.67.3",
    "typing-extensions>=4.15.0",
    "urllib3>=2.7.0",
    "yarl>=1.24.2",
]
